import { supabase } from "@/integrations/supabase/client";
import {
  recordDeposit, recordWithdrawal, recordBuy, recordSell,
  recordPairedTransfer, recordManualAdjustment, ensureAsset,
} from "@/lib/ledger-actions";
import type { ParsedEntry, ParseSummary } from "./import-parser";

export interface ImportResult {
  batchId: string;
  imported: number;
  failed: number;
  errors: { lineNo: number; raw: string; message: string }[];
}

/**
 * A single row's committed footprint. Persisted inside
 * `import_batches.summary.row_records[]` so the Import Report / Batch Detail
 * view and the Advanced Rollback engine can inspect and reverse each row
 * without a separate table.
 */
export interface ImportRowRecord {
  lineNo: number;
  raw: string;
  kind: ParsedEntry["kind"];
  timestamp: string;
  amount: number;
  description: string | null;
  category: string | null;
  txIds: string[];
  transferGroupId?: string;
  accountId?: string;
  assetId?: string;
  goalId?: string;
  goalContribution?: number;
  createdAccountId?: string;
  createdAssetId?: string;
  createdGoalId?: string;
  skipped?: boolean;
  skippedReason?: string;
  error?: string;
}

async function uid() {
  const { data } = await supabase.auth.getUser();
  if (!data.user) throw new Error("Not authenticated");
  return data.user.id;
}

/**
 * Execute parsed entries through the existing ledger / goals primitives.
 * Each created transaction is tagged `import:<batchId>` so rollback can void
 * everything generated by this batch. Goals and assets created inline are also
 * tracked in the batch's `summary.created_*_ids` and `summary.row_records`.
 */
export async function executeImport(args: {
  sourceText: string;
  entries: ParsedEntry[];
  summary: ParseSummary;
  label?: string;
  skipDuplicates?: boolean;
  /** Base currency for inline-created accounts. Defaults to USD. */
  defaultCurrency?: string;
  /** Optional progress callback for large imports (Phase D UX). */
  onProgress?: (done: number, total: number) => void;
}): Promise<ImportResult> {
  const user_id = await uid();
  const { data: batch, error: bErr } = await (supabase as any)
    .from("import_batches")
    .insert({
      user_id, source_text: args.sourceText, summary: args.summary,
      label: args.label ?? null, imported_count: 0, error_count: 0, errors: [],
    })
    .select("id").single();
  if (bErr) throw bErr;
  const batchId = batch.id as string;
  const tag = `import:${batchId}`;

  const createdGoalIds: string[] = [];
  const createdAssetIds: string[] = [];
  const createdAccountIds: string[] = [];
  const rowRecords: ImportRowRecord[] = [];
  let duplicatesSkipped = 0;

  let imported = 0;
  const errors: ImportResult["errors"] = [];

  for (const e of args.entries) {
    const rec: ImportRowRecord = {
      lineNo: e.lineNo, raw: e.raw, kind: e.kind,
      timestamp: e.timestamp, amount: e.amount,
      description: e.description ?? null, category: e.category ?? null,
      txIds: [],
    };
    if (e.errors.length) {
      rec.error = e.errors.join("; ");
      errors.push({ lineNo: e.lineNo, raw: e.raw, message: rec.error });
      rowRecords.push(rec);
      continue;
    }
    if (args.skipDuplicates && e.duplicateOf) {
      rec.skipped = true; rec.skippedReason = "duplicate";
      duplicatesSkipped++;
      rowRecords.push(rec);
      continue;
    }
    try {
      switch (e.kind) {
        case "deposit": {
          const id = await depositTagged(e, tag, user_id);
          rec.txIds.push(id); rec.accountId = e.account!.matchedId!;
          imported++; break;
        }
        case "expense": {
          const id = await withdrawalTagged(e, tag, user_id);
          rec.txIds.push(id); rec.accountId = e.account!.matchedId!;
          imported++; break;
        }
        case "transfer": {
          const { txIds, groupId } = await transferTagged(e, tag, user_id);
          rec.txIds.push(...txIds); rec.transferGroupId = groupId;
          imported++; break;
        }
        case "buy": {
          const id = await buyTagged(e, tag, user_id);
          rec.txIds.push(id); rec.accountId = e.account?.matchedId ?? undefined;
          rec.assetId = e.asset?.matchedId ?? undefined;
          imported++; break;
        }
        case "sell": {
          const id = await sellTagged(e, tag, user_id);
          rec.txIds.push(id); rec.accountId = e.account?.matchedId ?? undefined;
          rec.assetId = e.asset?.matchedId ?? undefined;
          imported++; break;
        }
        case "account_open": {
          const { txId, accountId, createdAccountId } = await openAccountTagged(e, tag, user_id);
          rec.txIds.push(txId); rec.accountId = accountId;
          if (createdAccountId && !accountSeen.has(createdAccountId)) {
            rec.createdAccountId = createdAccountId;
            createdAccountIds.push(createdAccountId);
            accountSeen.add(createdAccountId);
          }
          imported++; break;
        }
        case "asset_open": {
          const { txId, assetId } = await openAssetTagged(e, tag, user_id);
          rec.txIds.push(txId); rec.assetId = assetId ?? undefined;
          if (assetId && !assetSeen.has(assetId)) { createdAssetIds.push(assetId); assetSeen.add(assetId); }
          imported++; break;
        }
        case "goal_create": {
          const { id, created } = await ensureGoal(e.goal?.matchedId ?? null, e.goal?.raw ?? "", e.targetAmount ?? 0);
          if (id) rec.goalId = id;
          if (created && id) { rec.createdGoalId = id; createdGoalIds.push(id); }
          imported++; break;
        }
        case "goal_contribution": {
          await contributeGoalTagged(e);
          rec.goalId = e.goal?.matchedId ?? undefined;
          rec.goalContribution = e.amount;
          imported++; break;
        }
        default: {
          const msg = `Unsupported kind: ${e.kind}`;
          rec.error = msg;
          errors.push({ lineNo: e.lineNo, raw: e.raw, message: msg });
        }
      }
    } catch (err: any) {
      const msg = err?.message ?? String(err);
      rec.error = msg;
      errors.push({ lineNo: e.lineNo, raw: e.raw, message: msg });
    }
    rowRecords.push(rec);
    args.onProgress?.(rowRecords.length, args.entries.length);
  }

  // Local dedupe sets are declared at module scope (accountSeen / assetSeen).
  void 0;

  const patchedSummary = {
    ...args.summary,
    created_goals: createdGoalIds.length,
    created_assets: createdAssetIds.length,
    created_accounts: createdAccountIds.length,
    created_goal_ids: createdGoalIds,
    created_asset_ids: createdAssetIds,
    created_account_ids: createdAccountIds,
    duplicates_skipped: duplicatesSkipped,
    imported_at: new Date().toISOString(),
    row_records: rowRecords,
  };


  await (supabase as any)
    .from("import_batches")
    .update({
      imported_count: imported,
      error_count: errors.length,
      errors,
      summary: patchedSummary,
    })
    .eq("id", batchId);

  return { batchId, imported, failed: errors.length, errors };
}

// module-scoped Sets used to dedupe entities across the loop
const assetSeen = new Set<string>();
const accountSeen = new Set<string>();

// ----- per-kind executors (return the created tx id(s)) -----

async function depositTagged(e: ParsedEntry, tag: string, user_id: string) {
  const tags = [tag]; if (e.category) tags.push(`cat:${e.category}`);
  const { data, error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "deposit",
    destination_account_id: e.account!.matchedId!,
    quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags,
  }).select("id").single();
  if (error) throw error;
  void recordDeposit; // kept for API parity
  return data.id as string;
}

async function withdrawalTagged(e: ParsedEntry, tag: string, user_id: string) {
  const tags = [tag]; if (e.category) tags.push(`cat:${e.category}`);
  const { data, error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "withdrawal",
    source_account_id: e.account!.matchedId!,
    quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags,
  }).select("id").single();
  if (error) throw error;
  void recordWithdrawal;
  return data.id as string;
}

async function transferTagged(e: ParsedEntry, tag: string, user_id: string) {
  const groupId = crypto.randomUUID();
  const tags = [tag];
  const { data, error } = await (supabase as any).from("transactions").insert([
    {
      user_id, transaction_type: "transfer",
      source_account_id: e.fromAccount!.matchedId!, destination_account_id: null,
      quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
      transfer_group_id: groupId, execution_timestamp: e.timestamp,
      note: e.description ?? undefined, tags,
    },
    {
      user_id, transaction_type: "transfer",
      source_account_id: null, destination_account_id: e.toAccount!.matchedId!,
      quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
      transfer_group_id: groupId, execution_timestamp: e.timestamp,
      note: e.description ?? undefined, tags,
    },
  ]).select("id");
  if (error) throw error;
  void recordPairedTransfer;
  return { txIds: (data ?? []).map((r: any) => r.id as string), groupId };
}

async function buyTagged(e: ParsedEntry, tag: string, user_id: string) {
  if (!e.asset?.matchedId || !e.account?.matchedId) throw new Error("Missing asset or account");
  const qty = e.quantity ?? 0;
  const price = e.price ?? 0;
  const fiat = qty * price || e.amount;
  const { data, error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "buy",
    source_account_id: e.account.matchedId,
    destination_account_id: e.account.matchedId,
    asset_id: e.asset.matchedId,
    quantity: qty, fiat_value: fiat, base_value: fiat,
    asset_price: price || null, exchange_rate: price || null,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags: [tag],
  }).select("id").single();
  if (error) throw error;
  void recordBuy;
  return data.id as string;
}

async function sellTagged(e: ParsedEntry, tag: string, user_id: string) {
  if (!e.asset?.matchedId || !e.account?.matchedId) throw new Error("Missing asset or account");
  const qty = e.quantity ?? 0;
  const price = e.price ?? 0;
  const fiat = qty * price || e.amount;
  const { data, error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "sell",
    source_account_id: e.account.matchedId,
    destination_account_id: e.account.matchedId,
    asset_id: e.asset.matchedId,
    quantity: qty, fiat_value: fiat, base_value: fiat,
    asset_price: price || null, exchange_rate: price || null,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags: [tag],
  }).select("id").single();
  if (error) throw error;
  void recordSell;
  return data.id as string;
}

async function openAccountTagged(
  e: ParsedEntry, tag: string, user_id: string,
): Promise<{ txId: string; accountId: string; createdAccountId?: string }> {
  let accountId = e.account?.matchedId ?? null;
  let createdAccountId: string | undefined;

  // Inline-create the account when the parser flagged it as new.
  if (!accountId) {
    const name = (e.account?.raw ?? "New account").trim() || "New account";
    const { data, error } = await (supabase as any)
      .from("accounts")
      .insert({ user_id, name, current_balance: 0 })
      .select("id")
      .single();
    if (error) throw new Error(`Failed to create account "${name}": ${error.message}`);
    accountId = data.id as string;
    createdAccountId = accountId;
  }

  // recordManualAdjustment returns the tx id it just inserted — no query-back,
  // no created_at ordering, no reliance on sequential execution.
  const txId = await recordManualAdjustment({
    accountId,
    newBalance: e.amount,
    note: e.description ?? "Opening balance (import)",
  });

  // Tag the exact tx we just created — deterministic and race-free.
  const { error: tagErr } = await (supabase as any).from("transactions")
    .update({ tags: [tag, "opening_balance"] })
    .eq("id", txId);
  if (tagErr) throw tagErr;

  return { txId, accountId, createdAccountId };
}

async function openAssetTagged(e: ParsedEntry, tag: string, user_id: string) {
  if (!e.asset?.matchedId) throw new Error("Asset not resolved");
  const qty = e.quantity ?? 0;
  const price = e.price ?? 0;
  const fiat = qty * price;
  const { data, error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "buy",
    asset_id: e.asset.matchedId,
    quantity: qty, fiat_value: fiat, base_value: fiat,
    asset_price: price || null,
    execution_timestamp: e.timestamp,
    note: e.description ?? "Opening position (import)",
    tags: [tag, "opening_position"],
  }).select("id").single();
  if (error) throw error;
  return { txId: data.id as string, assetId: e.asset.matchedId };
}

async function ensureGoal(matchedId: string | null, name: string, target: number): Promise<{ id: string | null; created: boolean }> {
  const user_id = await uid();
  if (matchedId) {
    const { error } = await (supabase as any).from("goals").update({ target_amount: target }).eq("id", matchedId);
    if (error) throw error;
    return { id: matchedId, created: false };
  }
  const { data, error } = await (supabase as any).from("goals").insert({
    user_id, name, target_amount: target, current_amount: 0, kind: "custom",
  }).select("id").single();
  if (error) throw error;
  return { id: data.id as string, created: true };
}

async function contributeGoalTagged(e: ParsedEntry) {
  if (!e.goal?.matchedId) throw new Error("Goal not resolved");
  const { data: g, error: gErr } = await (supabase as any)
    .from("goals").select("current_amount").eq("id", e.goal.matchedId).single();
  if (gErr) throw gErr;
  const next = Number(g?.current_amount ?? 0) + e.amount;
  const { error } = await (supabase as any).from("goals")
    .update({ current_amount: next }).eq("id", e.goal.matchedId);
  if (error) throw error;
  void ensureAsset;
}

/**
 * Batch-level rollback (kept for backwards compatibility with the sidebar
 * "Rollback" button). Advanced partial rollback lives in `import-rollback.ts`
 * and is preferred for the Import Report UI.
 */
export async function rollbackImport(batchId: string): Promise<{ voided: number }> {
  const tag = `import:${batchId}`;
  const { data, error } = await (supabase as any)
    .from("transactions").select("id").contains("tags", [tag]).is("voided_at", null);
  if (error) throw error;
  const ids = (data ?? []).map((r: { id: string }) => r.id);
  if (ids.length) {
    const { error: upErr } = await (supabase as any)
      .from("transactions")
      .update({ voided_at: new Date().toISOString(), voided_reason: "Import rollback" })
      .in("id", ids);
    if (upErr) throw upErr;
  }
  await (supabase as any).from("import_batches")
    .update({ rolled_back_at: new Date().toISOString() }).eq("id", batchId);
  return { voided: ids.length };
}
