import { supabase } from "@/integrations/supabase/client";
import {
  recordDeposit, recordWithdrawal, recordBuy, recordSell,
  recordPairedTransfer, recordManualAdjustment, ensureAsset,
} from "@/lib/ledger-actions";
import type { ParsedEntry, ParseSummary } from "./import-parser";

export interface ImportResult {
  batchId: string;
  imported: number;
  failed: number;
  errors: { lineNo: number; raw: string; message: string }[];
}

async function uid() {
  const { data } = await supabase.auth.getUser();
  if (!data.user) throw new Error("Not authenticated");
  return data.user.id;
}

/**
 * Execute parsed entries through the existing ledger / goals primitives.
 * Each created transaction is tagged `import:<batchId>` so rollback can void
 * everything generated by this batch. Goals and assets created inline are also
 * tracked in the batch's `summary.created_*` for the History panel.
 */
export async function executeImport(args: {
  sourceText: string;
  entries: ParsedEntry[];
  summary: ParseSummary;
  label?: string;
  skipDuplicates?: boolean;
}): Promise<ImportResult> {
  const user_id = await uid();
  const { data: batch, error: bErr } = await (supabase as any)
    .from("import_batches")
    .insert({
      user_id, source_text: args.sourceText, summary: args.summary,
      label: args.label ?? null, imported_count: 0, error_count: 0, errors: [],
    })
    .select("id").single();
  if (bErr) throw bErr;
  const batchId = batch.id as string;
  const tag = `import:${batchId}`;
  const createdGoals: string[] = [];
  const createdAssets: string[] = [];

  let imported = 0;
  const errors: ImportResult["errors"] = [];

  for (const e of args.entries) {
    if (e.errors.length) {
      errors.push({ lineNo: e.lineNo, raw: e.raw, message: e.errors.join("; ") });
      continue;
    }
    if (args.skipDuplicates && e.duplicateOf) continue;
    try {
      switch (e.kind) {
        case "deposit":
          await depositTagged(e, tag); imported++; break;
        case "expense":
          await withdrawalTagged(e, tag); imported++; break;
        case "transfer":
          await transferTagged(e, tag); imported++; break;
        case "buy":
          await buyTagged(e, tag); imported++; break;
        case "sell":
          await sellTagged(e, tag); imported++; break;
        case "account_open":
          await openAccountTagged(e, tag); imported++; break;
        case "asset_open": {
          const id = await openAssetTagged(e, tag);
          if (id) createdAssets.push(id);
          imported++; break;
        }
        case "goal_create": {
          const id = await ensureGoal(e.goal?.matchedId ?? null, e.goal?.raw ?? "", e.targetAmount ?? 0);
          if (id) createdGoals.push(id);
          imported++; break;
        }
        case "goal_contribution":
          await contributeGoalTagged(e); imported++; break;
        default:
          errors.push({ lineNo: e.lineNo, raw: e.raw, message: `Unsupported kind: ${e.kind}` });
      }
    } catch (err: any) {
      errors.push({ lineNo: e.lineNo, raw: e.raw, message: err?.message ?? String(err) });
    }
  }

  await (supabase as any)
    .from("import_batches")
    .update({
      imported_count: imported,
      error_count: errors.length,
      errors,
      summary: { ...args.summary, created_goals: createdGoals.length, created_assets: createdAssets.length },
    })
    .eq("id", batchId);

  return { batchId, imported, failed: errors.length, errors };
}

// ----- per-kind executors -----

async function depositTagged(e: ParsedEntry, tag: string) {
  const tags = [tag]; if (e.category) tags.push(`cat:${e.category}`);
  await recordDeposit({
    destinationAccountId: e.account!.matchedId!,
    amount: e.amount,
    ts: e.timestamp,
    note: e.description ?? undefined,
    tags,
  });
}

async function withdrawalTagged(e: ParsedEntry, tag: string) {
  const user_id = await uid();
  const tags = [tag]; if (e.category) tags.push(`cat:${e.category}`);
  const { error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "withdrawal",
    source_account_id: e.account!.matchedId!,
    quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags,
  });
  if (error) throw error;
  void recordWithdrawal; // keep import alive for future use
}

async function transferTagged(e: ParsedEntry, tag: string) {
  const user_id = await uid();
  const groupId = crypto.randomUUID();
  const tags = [tag];
  const { error } = await (supabase as any).from("transactions").insert([
    {
      user_id, transaction_type: "transfer",
      source_account_id: e.fromAccount!.matchedId!, destination_account_id: null,
      quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
      transfer_group_id: groupId, execution_timestamp: e.timestamp,
      note: e.description ?? undefined, tags,
    },
    {
      user_id, transaction_type: "transfer",
      source_account_id: null, destination_account_id: e.toAccount!.matchedId!,
      quantity: e.amount, fiat_value: e.amount, base_value: e.amount,
      transfer_group_id: groupId, execution_timestamp: e.timestamp,
      note: e.description ?? undefined, tags,
    },
  ]);
  if (error) throw error;
  void recordPairedTransfer;
}

async function buyTagged(e: ParsedEntry, tag: string) {
  const user_id = await uid();
  if (!e.asset?.matchedId || !e.account?.matchedId) throw new Error("Missing asset or account");
  const qty = e.quantity ?? 0;
  const price = e.price ?? 0;
  const fiat = qty * price || e.amount;
  const { error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "buy",
    source_account_id: e.account.matchedId,
    destination_account_id: e.account.matchedId, // single-account buy; holdings derived
    asset_id: e.asset.matchedId,
    quantity: qty, fiat_value: fiat, base_value: fiat,
    asset_price: price || null, exchange_rate: price || null,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags: [tag],
  });
  if (error) throw error;
  void recordBuy;
}

async function sellTagged(e: ParsedEntry, tag: string) {
  const user_id = await uid();
  if (!e.asset?.matchedId || !e.account?.matchedId) throw new Error("Missing asset or account");
  const qty = e.quantity ?? 0;
  const price = e.price ?? 0;
  const fiat = qty * price || e.amount;
  const { error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "sell",
    source_account_id: e.account.matchedId,
    destination_account_id: e.account.matchedId,
    asset_id: e.asset.matchedId,
    quantity: qty, fiat_value: fiat, base_value: fiat,
    asset_price: price || null, exchange_rate: price || null,
    execution_timestamp: e.timestamp,
    note: e.description ?? undefined,
    tags: [tag],
  });
  if (error) throw error;
  void recordSell;
}

async function openAccountTagged(e: ParsedEntry, tag: string) {
  // Opening balance = manual_adjustment to set current_balance to e.amount.
  if (!e.account?.matchedId) throw new Error("Account not resolved");
  await recordManualAdjustment({
    accountId: e.account.matchedId,
    newBalance: e.amount,
    note: e.description ?? "Opening balance (import)",
  });
  // tag the just-inserted tx
  const user_id = await uid();
  await (supabase as any)
    .from("transactions")
    .update({ tags: [tag, "opening_balance"] })
    .eq("user_id", user_id)
    .eq("destination_account_id", e.account.matchedId)
    .eq("transaction_type", "manual_adjustment")
    .order("created_at", { ascending: false }).limit(1);
}

async function openAssetTagged(e: ParsedEntry, tag: string): Promise<string | null> {
  // Treat as a buy with the avg cost basis. If no account given, skip cash leg —
  // record qty * avg as a `buy` with destination only.
  const user_id = await uid();
  if (!e.asset?.matchedId) throw new Error("Asset not resolved");
  const qty = e.quantity ?? 0;
  const price = e.price ?? 0;
  const fiat = qty * price;
  const { error } = await (supabase as any).from("transactions").insert({
    user_id,
    transaction_type: "buy",
    asset_id: e.asset.matchedId,
    quantity: qty, fiat_value: fiat, base_value: fiat,
    asset_price: price || null,
    execution_timestamp: e.timestamp,
    note: e.description ?? "Opening position (import)",
    tags: [tag, "opening_position"],
  });
  if (error) throw error;
  return e.asset.matchedId;
}

async function ensureGoal(matchedId: string | null, name: string, target: number): Promise<string | null> {
  const user_id = await uid();
  if (matchedId) {
    const { error } = await (supabase as any).from("goals").update({ target_amount: target }).eq("id", matchedId);
    if (error) throw error;
    return matchedId;
  }
  const { data, error } = await (supabase as any).from("goals").insert({
    user_id, name, target_amount: target, current_amount: 0, kind: "custom",
  }).select("id").single();
  if (error) throw error;
  return data.id as string;
}

async function contributeGoalTagged(e: ParsedEntry) {
  if (!e.goal?.matchedId) throw new Error("Goal not resolved");
  // Goals are not on the ledger — contributions update goals.current_amount directly.
  const { data: g, error: gErr } = await (supabase as any)
    .from("goals").select("current_amount").eq("id", e.goal.matchedId).single();
  if (gErr) throw gErr;
  const next = Number(g?.current_amount ?? 0) + e.amount;
  const { error } = await (supabase as any).from("goals")
    .update({ current_amount: next }).eq("id", e.goal.matchedId);
  if (error) throw error;
  void ensureAsset;
}

/** Void every transaction tagged with this batch id (soft delete). */
export async function rollbackImport(batchId: string): Promise<{ voided: number }> {
  const tag = `import:${batchId}`;
  const { data, error } = await (supabase as any)
    .from("transactions").select("id").contains("tags", [tag]).is("voided_at", null);
  if (error) throw error;
  const ids = (data ?? []).map((r: { id: string }) => r.id);
  if (ids.length) {
    const { error: upErr } = await (supabase as any)
      .from("transactions")
      .update({ voided_at: new Date().toISOString(), voided_reason: "Import rollback" })
      .in("id", ids);
    if (upErr) throw upErr;
  }
  await (supabase as any).from("import_batches")
    .update({ rolled_back_at: new Date().toISOString() }).eq("id", batchId);
  return { voided: ids.length };
}
