begin;
select plan(12);
insert into auth.users (id,email,raw_user_meta_data) values ('55555555-5555-4555-8555-555555555555','workflow@example.test','{}'::jsonb);
set local role authenticated;
select set_config('request.jwt.claim.sub','55555555-5555-4555-8555-555555555555',true);
select lives_ok($$select public.v2_complete_onboarding('{"displayName":"Workflow","baseCurrency":"EUR","locale":"en-US"}'::jsonb)$$,'onboard');
select lives_ok($$select public.v2_put_asset('{"id":"asset:eur","symbol":"EUR","name":"Euro","kind":"fiat","precision":2,"fiatCurrency":"EUR"}'::jsonb)$$,'create base asset');
select lives_ok($$select public.v2_put_asset('{"id":"asset:unused","symbol":"ZZZ","name":"Unused","kind":"other","precision":4,"fiatCurrency":null}'::jsonb)$$,'create unused asset');
select lives_ok($$select public.v2_append_price_quote('{"assetId":"asset:unused","amount":"12.5","currency":"EUR","asOf":"2026-08-20T08:00:00Z","source":"manual"}'::jsonb)$$,'unused asset can have quote history');
select lives_ok($$select public.v2_delete_unused_asset('asset:unused')$$,'unused asset can be deleted');
select is((select count(*)::integer from public.v2_assets where id='asset:unused'),0,'asset removed');
select is((select count(*)::integer from public.v2_price_quotes where asset_id='asset:unused'),0,'orphan quote history removed atomically');
select throws_ok($$select public.v2_delete_unused_asset('asset:eur')$$,'P0001','base currency asset cannot be deleted','base currency protected');
select lives_ok($$select public.v2_save_weekly_review('{"id":"review:final","weekStart":"2026-08-17","reportedPnl":"100","winRate":"60","avgRr":"2","tradeCount":5,"maxDrawdownPct":"3","disciplineScore":80,"psychologyScore":80,"notes":null,"lessons":null}'::jsonb,true)$$,'direct final weekly save succeeds');
select is((select is_draft from public.v2_weekly_reviews where id='review:final'),false,'direct save is final');
select lives_ok($$select public.v2_save_weekly_review('{"id":"review:draft","weekStart":"2026-08-24","reportedPnl":"0","winRate":"0","avgRr":"0","tradeCount":0,"maxDrawdownPct":"0","disciplineScore":70,"psychologyScore":70,"notes":null,"lessons":null}'::jsonb,false)$$,'save as draft succeeds');
select is((select is_draft from public.v2_weekly_reviews where id='review:draft'),true,'draft remains editable');
select lives_ok($$select public.v2_save_weekly_review('{"id":"review:draft","weekStart":"2026-08-24","reportedPnl":"25","winRate":"50","avgRr":"1.5","tradeCount":2,"maxDrawdownPct":"1","disciplineScore":75,"psychologyScore":75,"notes":null,"lessons":null}'::jsonb,true)$$,'draft can be atomically saved final');
select is((select is_draft from public.v2_weekly_reviews where id='review:draft'),false,'draft becomes final');
select * from finish();
rollback;
